[build]
[build.frontend]
builder = "nixpacks"
watchPatterns = ["/frontend/**"]

# [build.backend]
# builder = "dockerfile"
# dockerfilePath = "backend/auth/Dockerfile"
# watchPatterns = ["/backend/**"]
# buildCommand = "cd backend && go build"

[build.backend]
builder = "dockerfile"
dockerfilePath = "backend/auth/Dockerfile"
watchPatterns = ["/backend/**"]
