[services]
[services.frontend]
type = "nixpacks"
path = "frontend"
buildCmd = "npm install && npm run build"
startCmd = "npm run start"

# [services.backend]
# type = "docker"
# dockerfile = "Dockerfile"
# buildContext = "backend/auth"
