[services]

  [services.frontend]
  buildType = "nixpacks"
  path = "frontend"
  buildCommand = "npm install && npm run build"
  startCommand = "npm run start"

  [services.backend]
  buildType = "docker"
  path = "backend/auth"
  dockerfile = "Dockerfile"
