[services]
[services.frontend]
type = "nixpacks"
# Говорим, что корень Nixpacks-проекта — папка frontend
path = "frontend"
watchPatterns = ["frontend/**"]

[services.backend]
type = "docker"
dockerfile = "Dockerfile"
buildContext = "backend"
watchPatterns = ["backend/**"]
