// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/28/2024, 5:05:09 AM
const configMerger = require("/Users/rgeraev/dev/flippy-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/rgeraev/dev/flippy-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rgeraev/dev/flippy-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rgeraev/dev/flippy-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rgeraev/dev/flippy-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rgeraev/dev/flippy-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rgeraev/dev/flippy-app/plugins/**/*.{js,ts,mjs}","/Users/rgeraev/dev/flippy-app/composables/**/*.{js,ts,mjs}","/Users/rgeraev/dev/flippy-app/utils/**/*.{js,ts,mjs}","/Users/rgeraev/dev/flippy-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rgeraev/dev/flippy-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rgeraev/dev/flippy-app/app.config.{js,ts,mjs}"] } }));

module.exports = config
